version: "3.1"
services:
  app:
    image: dadash
    container_name: dadash_php
    build: 
      context: .
      dockerfile: .
    restart: "no"
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
   
    networks:
      - dadash

    command: "php artisan serve --host=0.0.0.0 --port=8000"

   

  db:
    image: mysql:latest
    container_name: mysql_db_dadash
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - dadash
   
  
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    restart: "no"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - dadash


networks:
  dadash:
    driver: bridge



volumes:
  db-data:
  